repos:
  - repo: local
    hooks:
      - id: indicator-lint
        name: Indicator lint
        entry: make lint
        language: system
        pass_filenames: false
      - id: indicator-test
        name: Indicator tests and coverage
        entry: make test
        language: system
        pass_filenames: false
