ANCHOR = "R_100"

US_LEADER = "R_50"
US_ALT_A = "R_25"
US_ALT_B = "R_10"

EU_LEADER = "R_75"
EU_ALT_A = "1HZ50V"
EU_ALT_B = "1HZ100V"

US_CLUSTER = (US_ALT_B, US_ALT_A, US_LEADER)
EU_CLUSTER = (EU_LEADER, EU_ALT_A, EU_ALT_B)

ALL_SYMBOLS = (ANCHOR, *US_CLUSTER, *EU_CLUSTER)
