ANCHOR = "frxEURUSD"

US_LEADER = "OTC_DJI"
US_ALT_A = "OTC_SPC"
US_ALT_B = "OTC_NDX"

EU_LEADER = "OTC_FCHI"
EU_ALT_A = "OTC_SSMI"
EU_ALT_B = "OTC_GDAXI"

US_CLUSTER = (US_ALT_A, US_ALT_B, US_LEADER)
EU_CLUSTER = (EU_LEADER, EU_ALT_A, EU_ALT_B, "OTC_FTSE")

ALL_SYMBOLS = (ANCHOR, *US_CLUSTER, *EU_CLUSTER)
