from src.domain.symbols.drift_symbols import DEFAULT_ANCHOR, DRIFT_SYMBOLS, HEDGE_PEER, TRADING_SYMBOLS


ANCHOR = DEFAULT_ANCHOR
PAIR = DEFAULT_ANCHOR
ALT_SYMBOL = "R_50"
HEDGE_PEER_SYMBOL = DEFAULT_ANCHOR
LOW_SIDE_SYMBOL = DEFAULT_ANCHOR
HIGH_SIDE_SYMBOL = DEFAULT_ANCHOR
ALL_SYMBOLS = TRADING_SYMBOLS
PAIR_CLUSTER = tuple(s for s in DRIFT_SYMBOLS if s != ANCHOR)
HEDGE_PEER_MAP = HEDGE_PEER
